server:
  port: 9900
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&nullCatalogMeansCurrent=true
    username: {cipher}eb6a612fc2279931a20f867c2db6cdfbc785232f47729a451b26db672f2c85b4
    password: {cipher}de8f3c248e02b580f2812cb60963df1ce4a05025edc7cf6605baa1c039a12d9e
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  application:
    name: provider-application-name

test:
  emp:
    ename: qwe
  hh: 123
eureka:
  instance:
    #每间隔2s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我10s之内没有给你发心跳，就代表我故障了，将我踢出掉
    lease-expiration-duration-in-seconds: 10
    #告诉服务端，服务实例以IP作为链接，而不是取机器名
    prefer-ip-address: true
    #告诉服务端，这个服务实例的名字
    instance-id: provider-instance-id-9900
  client:
    #eureka注册中心的连接地址
#    service-url.defaultZone: http://e8761:8761/eureka,http://e8762:8762/eureka,http://e8763:8763/eureka
    service-url.defaultZone: http://e8761:8761/eureka