server:
  port: 8080
#  servlet:
#    context-path: /consumer

spring:
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  application:
    name: consumer
  cloud:
    loadbalancer:
      enabled: true

eureka:
  instance:
    #每间隔2s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 2
    #告诉服务端，如果我10s之内没有给你发心跳，就代表我故障了，将我踢出掉
    lease-expiration-duration-in-seconds: 10
    #告诉服务端，服务实例以IP作为链接，而不是取机器名
    prefer-ip-address: true
    #告诉服务端，这个服务实例的名字
    instance-id: consumer
    ip-address: 127.0.0.1
    appname: consumer1
  client:
    #eureka注册中心的连接地址
#    service-url.defaultZone: http://e8761:8761/eureka,http://e8762:8762/eureka,http://e8763:8763/eureka
    service-url:
      defaultZone: http://e8761:8761/eureka
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
  circuitbreaker:
    enabled: true
  metrics:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
ribbon:
  eager-load:
    clients:
